fragment PostParts on Post {
  __typename
  title
  slug
  excerpt
  category
  tags
  publishedAt
  updatedAt
  author
  coverImage
  ogImage
  featured
  sidebarFeatured
  draft
  seoTitle
  seoDescription
  canonicalUrl
  readingTime
  order
  viewCount
  relatedPosts
}
